linters:
  disable-all: true
  enable:
    # default
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    # none default
    - asciicheck
    - errorlint
    - errname
    - exhaustive
#    - exportloopref
#    - forbidigo
#    - funlen
#    - gci
#    - gochecknoglobals
#    - gochecknoinits
#    - gocognit
#    - goconst
#    - gocritic
#    - gocyclo
#    - godot
#    - godox
#    - goerr113
    - gofumpt
#    - goheader
#    - gomnd
#    - gomoddirectives
#    - gomodguard
#    - goprintffuncname
#    - gosec
#    - ifshort
#    - importas
#    - lll
#    - makezero
#    - misspell
#    - nakedret
#    - nestif
#    - nilerr
#    - nlreturn
#    - noctx
#    - nolintlint
#    - paralleltest
#    - prealloc
#    - predeclared
#    - promlinter
#    - revive
#    - rowserrcheck
#    - sqlclosecheck
#    - stylecheck
#    - tagliatelle
#    - testpackage
#    - thelper
#    - tparallel
#    - unconvert
#    - unparam
#    - wastedassign
#    - whitespace
    - wrapcheck
#    - wsl

linters-settings:
  wrapcheck:
    ignoreSigs:
      - .Errorf(
      - errors.New(
      - errors.Unwrap(
      - .Wrap(
      - .Wrapf(
      - .WithMessage(
      - .WithMessagef(
      - .WithStack(
    ignoreSigRegexps:
      - \.New.*Error\(
