linters:
  disable-all: true
  enable:
    # default
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    # none default
    - asciicheck
    - errorlint
    - errname
    - exhaustive
    - gocritic
    - gofumpt
    - gosec
    - ifshort
#    - lll
    - nolintlint
#    - paralleltest
    - prealloc
    - predeclared
    - revive
    - stylecheck
#    - tagliatelle
#    - testpackage
    - thelper
    - unconvert
    - unparam
    - wrapcheck
#    - wsl

linters-settings:
  wrapcheck:
    ignoreSigs:
      - .Errorf(
      - errors.New(
      - errors.Unwrap(
      - .Wrap(
      - .Wrapf(
      - .WithMessage(
      - .WithMessagef(
      - .WithStack(
    ignoreSigRegexps:
      - \.New.*Error\(
