version: '3.4'

services:
  postgres95:
    image: postgres:9.5
    ports:
      - "55432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pgpass
      - POSTGRES_DB=testdb
  postgres13:
    image: postgres:13.1
    ports:
      - "55413:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pgpass
      - POSTGRES_DB=testdb
  mysql56:
    image: mysql:5.6
    ports:
      - "33306:3306"
    environment:
      - MYSQL_DATABASE=testdb
      - MYSQL_ROOT_PASSWORD=mypass
  mysql80:
    image: mysql:8
    ports:
      - "33308:3306"
    environment:
      - MYSQL_DATABASE=testdb
      - MYSQL_ROOT_PASSWORD=mypass
    # docker安全验证
    security_opt:
      - seccomp:unconfined
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - './build/mysql/data:/var/lib/mysql'
      - './build/mysql/conf.d:/etc/mysql/conf.d'
      - './build/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d'
      - './build/mysql/sql:/opt/sql'
  mariadb:
    image: mariadb:10.5
    ports:
      - "33309:3306"
    environment:
      - MYSQL_DATABASE=testdb
      - MYSQL_ROOT_PASSWORD=mypass
