version: '3.4'
services:
  mysql80:
    image: mysql:8.0
    ports:
      - "33306:3306"
    environment:
      - MYSQL_DATABASE=testdb
      - MYSQL_ROOT_PASSWORD=mypass
    # docker安全验证
    security_opt:
      - seccomp:unconfined
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - './build/mysql/conf.d:/etc/mysql/conf.d'
      - './build/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d'
      - './build/mysql/sql:/opt/sql'
  mysql57:
    image: mysql:5.7
    ports:
      - "33307:3306"
    environment:
      - MYSQL_DATABASE=testdb
      - MYSQL_ROOT_PASSWORD=mypass
    volumes:
      - './build/mysql/conf.d:/etc/mysql/conf.d'
      - './build/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d'
      - './build/mysql/sql:/opt/sql'
  mariadb:
    image: mariadb:10.5
    ports:
      - "33308:3306"
    environment:
      - MYSQL_DATABASE=testdb
      - MYSQL_ROOT_PASSWORD=mypass
    volumes:
      - './build/mysql/conf.d:/etc/mysql/conf.d'
      - './build/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d'
      - './build/mysql/sql:/opt/sql'
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - "38080:8080"
