version: '3.4'

services:
  postgres95:
    image: postgres:9.5
    restart: always
    ports:
      - "55432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pgpass
      - POSTGRES_DB=testdb
  postgres:
    image: postgres:13.1
    restart: always
    ports:
      - "55413:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pgpass
      - POSTGRES_DB=testdb
  mysql56:
    image: mysql:5.6
    restart: always
    ports:
      - "33306:3306"
    environment:
      - MYSQL_DATABASE=testdb
      - MYSQL_ROOT_PASSWORD=mypass
  mysql:
    image: mysql:8
    restart: always
    ports:
      - "33308:3306"
    environment:
      - MYSQL_DATABASE=testdb
      - MYSQL_ROOT_PASSWORD=mypass
  mariadb:
    image: mariadb:10.5
    restart: always
    ports:
      - "33309:3306"
    environment:
      - MYSQL_DATABASE=testdb
      - MYSQL_ROOT_PASSWORD=mypass
