// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Column struct {
	Name            string      `json:"name"`
	Type            string      `json:"type"`
	Nullable        bool        `json:"nullable"`
	Default         *string     `json:"default"`
	Comment         *string     `json:"comment"`
	ExtraDef        *string     `json:"extraDef"`
	ParentRelations []*Relation `json:"parentRelations"`
	ChildRelations  []*Relation `json:"childRelations"`
}

type Constraint struct {
	Name              string   `json:"name"`
	Type              string   `json:"type"`
	Def               string   `json:"def"`
	Table             *string  `json:"table"`
	ReferencedTable   *string  `json:"referencedTable"`
	Columns           []string `json:"columns"`
	ReferencedColumns []string `json:"referencedColumns"`
	Comment           *string  `json:"comment"`
}

type Index struct {
	Name    string    `json:"name"`
	Def     string    `json:"def"`
	Table   *string   `json:"table"`
	Columns []*string `json:"columns"`
	Comment *string   `json:"comment"`
}

type Relation struct {
	Table         *Table    `json:"table"`
	Columns       []*Column `json:"columns"`
	ParentTable   *Table    `json:"parentTable"`
	ParentColumns []*Column `json:"parentColumns"`
	Def           *string   `json:"def"`
	Virtual       *bool     `json:"virtual"`
}

type Table struct {
	Name             string        `json:"name"`
	Type             string        `json:"type"`
	Comment          *string       `json:"comment"`
	Def              string        `json:"def"`
	CreatedAt        *time.Time    `json:"createdAt"`
	Columns          []*Column     `json:"columns"`
	Indexes          []*Index      `json:"indexes"`
	Constraints      []*Constraint `json:"constraints"`
	Triggers         []*Trigger    `json:"triggers"`
	ReferencedTables []*Table      `json:"referencedTables"`
}

type Trigger struct {
	Name    string  `json:"name"`
	Def     string  `json:"def"`
	Comment *string `json:"comment"`
}
