// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Table struct {
	Name      string `json:"name"`
	Type      string `json:"type"`
	Comment   string `json:"comment"`
	Def       string `json:"def"`
	CreatedAt string `json:"createdAt"`
}
