// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type TableInfo struct {
	Name      string     `json:"name"`
	Type      string     `json:"type"`
	Comment   *string    `json:"comment"`
	Def       string     `json:"def"`
	CreatedAt *time.Time `json:"createdAt"`
}
