on: [push, pull_request]
name: lint
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: fmt
      run: make fmt

    - name: lint
      run: make lint
