on: [push, pull_request]
name: test
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: bitnami/mysql:8.0.20
        env:
          ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: mypass
          MYSQL_DATABASE: testdb
          MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
        ports:
          - 33308:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
    - uses: actions/checkout@v2

    - name: Set up mysql
      run: mysql --host 127.0.0.1 --port 33308 -uroot -pmypass < build/mysql/sql/ddl.sql

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Test
      run: make test
